In [12]:
import numpy as np

zeros1 = np.zeros(3)
print(zeros1)

zeros = np.zeros((2, 3))
print(zeros)

ones = np.ones((3, 3))
print(ones)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
import numpy as np

arr = np.array([[1, 2],[3, 4]])
print(arr.size)

arr1 = np.array([[1, 2, 3],[2, 3, 4],[4, 5, 5],[6, 7, 6]])
print(arr1.size)
print(arr1)
print(arr)
print(type(arr))

4
12
[[1 2 3]
 [2 3 4]
 [4 5 5]
 [6 7 6]]
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [14]:
import numpy as np

a = np.arange(1, 7)
print(a)

b = a.reshape(3, 2)
print(b)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [15]:
import numpy as np

arr = np.array([[1,2],[3,4],[5,6]])

print(arr[-1])      
print(arr[1][0])    

arr1 = np.array([[[1,2],[2,3]],[[3,4],[3,5]]])

print(arr1[0])      

[5 6]
3
[[1 2]
 [2 3]]


In [16]:
import numpy as np

a = np.array([10,20,30,40])
b = np.array([40,50,60,70])

print(np.sum(a))
print(np.sum(b))
print(np.max(a))
print(np.max(b))
print(a+b)
print(a/b)
print(a+10)
print(a*3)
print(np.std(a))
print(np.std(b))
print(a%b)
print(np.mean(a))
print(np.mean(b))

100
220
40
70
[ 50  70  90 110]
[0.25       0.4        0.5        0.57142857]
[20 30 40 50]
[ 30  60  90 120]
11.180339887498949
11.180339887498949
[10 20 30 40]
25.0
55.0


In [17]:
import numpy as np

arr = np.array([[10,20,30],[40,50,60]])
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

[50 70 90]
[ 60 150]


In [18]:
import numpy as np

a = np.array([5,6,7,8])

print(a + 10)

[15 16 17 18]


In [19]:
import numpy as np

a = np.array([[5,6,7],[8,9,10]])  

b = np.array([1,2,3])    

print(a + b)

[[ 6  8 10]
 [ 9 11 13]]


In [2]:
import numpy as np

a = np.array([6,7,8])
b = np.array([8,9,10])

print(np.dot(a, b))

191


In [4]:
import numpy as np

a = np.array([[10,20],[30,40]])

b = np.array([[50,60],[70,80]])

print(a @ b)

[[1900 2200]
 [4300 5000]]


In [5]:
import numpy as np

a = np.array([[7,8],[9,10],[11,12]])

print(a.T)

[[ 7  9 11]
 [ 8 10 12]]


In [7]:
import numpy as np

a = np.array([[1,2,5],[3,4,6],[3,4,5]])

print(np.linalg.det(a))

2.0000000000000004


In [9]:
import numpy as np

a = np.array([[1,2,5],[3,4,6],[3,4,5]])

print(np.linalg.inv(a))

[[-2.   5.  -4. ]
 [ 1.5 -5.   4.5]
 [-0.   1.  -1. ]]


In [11]:
import numpy as np

a = np.array([[1,3,4],[5,7,10],[6,8,9]])

print(np.linalg.norm(a))

19.519221295943137


In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([3,4,5])

c = np.vstack((a, b))
print(c)

[[1 2 3]
 [3 4 5]]


In [2]:
import numpy as np

arr1 = np.array([6,7,8])
arr2 = np.array([8,9,10])

c = np.hstack((arr1,arr2))
print(c)

[ 6  7  8  8  9 10]


In [3]:
import numpy as np

arr1 = np.arange(20)
arr2 = np.split(arr1, 5)

print(arr2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]), array([12, 13, 14, 15]), array([16, 17, 18, 19])]


In [4]:
import numpy as np

arr = np.random.rand(3,3)
print(arr)

[[0.99933491 0.36787748 0.81711608]
 [0.12210312 0.40602155 0.21500962]
 [0.4234765  0.32228847 0.63036743]]


In [ ]:
import numpy as np

arr = np.random.randint(1, 20, size=(3,3))
print(arr)

In [ ]:
import numpy as np

arr = np.random.randint(1,15, size=(3,3))
print(arr)

variance = np.var(arr)
print(variance)

median = np.median(arr)
print(median)

In [ ]:
import numpy as np

arr = np.random.randint(1,15, size=(3,3))
print(arr)

percentile = np.percentile(arr, 75)
print(percentile)